/* eslint-disable @typescript-eslint/no-require-imports -- Standalone CommonJS QA harness. */
const {chromium}=require('playwright');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const output=process.env.QA_OUTPUT?path.resolve(root,process.env.QA_OUTPUT):path.join(root,'artifacts','qa-mail');
const temp=path.join(root,'artifacts','tmp');
fs.mkdirSync(output,{recursive:true});fs.mkdirSync(temp,{recursive:true});
const baseURL=process.env.QA_URL||'http://127.0.0.1:3097';
const results={baseURL,date:new Date().toISOString(),checks:[],viewports:[],errors:[],imageResponses:[]};
function check(name,value){assert.ok(value,name);results.checks.push(name);}
const titles=['Estrategia & Research','Estructuración Empresarial','Diseño & Marca','Tecnología & Software','IA & Automatización','Datos & Business Intelligence','Business Improvement'];
(async()=>{
 const context=await chromium.launchPersistentContext(path.join(temp,'chromium-qa'),{executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,viewport:{width:1440,height:900},reducedMotion:'reduce',env:{...process.env,TEMP:temp,TMP:temp},downloadsPath:temp});
 try{
 const page=await context.newPage();
 let expectingContactFailure=false;
 page.on('pageerror',e=>results.errors.push(e.message));
 page.on('console',m=>{if(m.type()==='error'&&!(expectingContactFailure&&m.text().includes('status of 502')))results.errors.push(m.text());});
 page.on('response',r=>{if(r.status()>=400&&!(expectingContactFailure&&r.url().startsWith('https://formsubmit.co/ajax/')))results.errors.push(`${r.status()} ${r.url()}`);if(r.url().includes('/_next/image'))results.imageResponses.push({status:r.status(),type:r.headers()['content-type']});});
 for(const [label,width,height] of [['desktop',1440,900],['laptop',1280,800],['tablet',768,1024],['mobile',390,844],['small-mobile',320,740]]){
  await page.setViewportSize({width,height});
  const response=await page.goto(baseURL,{waitUntil:'networkidle'});
  await page.evaluate(async()=>{await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})));});
  const dimensions=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,images:[...document.images].every(i=>i.complete&&i.naturalWidth>0)}));
  check(`${label}: HTTP 200`,response.status()===200);
  check(`${label}: no horizontal overflow`,dimensions.scroll<=width);
  check(`${label}: all images loaded`,dimensions.images);
  check(`${label}: updated official logo`,await page.locator('.brand-image').getAttribute('alt')==='ESCALA — Business Solutions S.A.S.'&&(await page.locator('.brand-image').getAttribute('src')).includes('escala-logo-sas.png'));
  check(`${label}: 3D hero replaces photograph`,await page.locator('.hero-depth-world').count()===1&&await page.locator('.hero-depth-ring').count()===4&&await page.locator('.hero-image').count()===0);
  check(`${label}: single h1`,await page.locator('h1').count()===1);
  check(`${label}: one active service`,await page.locator('.service-content h3').count()===1);
  check(`${label}: seven needs available`,await page.getByRole('tab').count()===7);
  check(`${label}: five process steps`,await page.locator('.process-accordion details').count()===5);
  check(`${label}: one process step expanded`,await page.locator('.process-accordion details[open]').count()===1);
  check(`${label}: generic photos removed`,await page.locator('img[src*="placeholder"],img[srcset*="placeholder"]').count()===0);
  await page.screenshot({path:path.join(output,`${label}-viewport.png`),animations:'disabled'});
  if(label==='desktop'||label==='mobile')await page.locator('.site-header').screenshot({path:path.join(output,`${label}-header.png`),animations:'disabled'});
  await page.setViewportSize({width,height:dimensions.height});
  await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
  await page.screenshot({path:path.join(output,`${label}.png`),fullPage:true,animations:'disabled'});
  await page.setViewportSize({width,height});
  results.viewports.push({label,width,height,contentHeight:dimensions.height});
 }
 await page.setViewportSize({width:1440,height:900});await page.goto(baseURL,{waitUntil:'networkidle'});
 check('Spanish document',await page.locator('html').getAttribute('lang')==='es');
 const font=await page.evaluate(async()=>{await document.fonts.ready;const family=getComputedStyle(document.querySelector('.hero h1 em')).fontFamily.split(',')[0].trim();return {family,loaded:document.fonts.check(`32px ${family}`)};});
 check('Fineday local font applied and loaded',font.family.toLowerCase().includes('fineday')&&font.loaded);
 const editorial=await page.evaluate(()=>['body','.navigation','.service-tabs button','.process-accordion h3'].every(selector=>getComputedStyle(document.querySelector(selector)).fontFamily.includes('Georgia')));
 check('Small text, navigation and controls use editorial serif',editorial);
 check('Ticker has all five disciplines',await page.locator('.hero-ticker-group').first().locator('span').count()===5);
 check('Ticker has no pause control',await page.locator('.ticker-toggle').count()===0);
 await page.emulateMedia({reducedMotion:'no-preference'});
 check('Hero route moves when motion is allowed',await page.locator('.hero-motion-route-line').evaluate(e=>getComputedStyle(e).animationName==='hero-route-flow'));
 check('Hero 3D camera moves when motion is allowed',await page.locator('.hero-depth-world').evaluate(e=>getComputedStyle(e).animationName==='hero-camera'));
 check('Ticker rolls when motion is allowed',await page.locator('.hero-ticker-track').evaluate(e=>getComputedStyle(e).animationName==='ticker-roll'));
 const firstPosition=await page.locator('.hero-ticker-track').evaluate(e=>getComputedStyle(e).transform);
 await page.waitForTimeout(180);
 check('Ticker keeps moving',await page.locator('.hero-ticker-track').evaluate((e,previous)=>getComputedStyle(e).transform!==previous,firstPosition));
 await page.emulateMedia({reducedMotion:'reduce'});
 check('Hero respects reduced motion',await page.locator('.hero-motion-route-line').evaluate(e=>getComputedStyle(e).animationName==='none'));
 check('Hero 3D camera respects reduced motion',await page.locator('.hero-depth-world').evaluate(e=>getComputedStyle(e).animationName==='none'));
 check('Ticker respects reduced motion',await page.locator('.hero-ticker-track').evaluate(e=>getComputedStyle(e).animationName==='none'));
 check('Preview noindex',(await page.locator('meta[name="robots"]').getAttribute('content')).includes('noindex'));
 await page.goto(baseURL,{waitUntil:'networkidle'});
 await page.keyboard.press('Tab');check('Skip link first focus',await page.locator('.skip-link').evaluate(e=>e===document.activeElement));await page.keyboard.press('Enter');check('Skip link targets main',new URL(page.url()).hash==='#contenido');
 await page.getByRole('link',{name:'Explorar soluciones',exact:true}).click();check('Explore CTA navigates',new URL(page.url()).hash==='#soluciones');
 const tabs=page.getByRole('tab');const visuals=new Set();
 await page.getByRole('button',{name:'Reproducir recorrido'}).click();check('Guided tour starts',await page.getByRole('button',{name:'Pausar recorrido'}).getAttribute('aria-pressed')==='true');
 await page.waitForFunction(()=>document.querySelector('#tab-estructuracion')?.getAttribute('aria-selected')==='true',undefined,{timeout:5000});
 check('Guided tour advances service automatically',await tabs.nth(1).getAttribute('aria-selected')==='true');
 await page.getByRole('button',{name:'Pausar recorrido'}).click();check('Guided tour pauses',await page.getByRole('button',{name:'Reproducir recorrido'}).getAttribute('aria-pressed')==='false');
 await page.getByRole('button',{name:'Reproducir recorrido'}).click();await tabs.nth(3).click();check('Manual selection stops guided tour',await page.getByRole('button',{name:'Reproducir recorrido'}).getAttribute('aria-pressed')==='false');
 for(let i=0;i<7;i++){
  await tabs.nth(i).click();
  check(`Service ${i+1}: selected`,await tabs.nth(i).getAttribute('aria-selected')==='true');
  check(`Service ${i+1}: content changes`,await page.locator('.service-content h3').textContent()===titles[i]);
  const photo=page.locator('.service-photo'); await photo.evaluate(i=>i.decode()); const visualTitle=await photo.getAttribute('alt'); visuals.add(await photo.getAttribute('src'));
  check(`Service ${i+1}: accessible photograph`,visualTitle.length>30);
  await page.locator('.service-panel').screenshot({path:path.join(output,`service-${i+1}.png`),animations:'disabled'});
  await page.getByRole('link',{name:'Conversemos',exact:true}).click();
  check(`Service ${i+1}: CTA reaches contact form`,new URL(page.url()).hash==='#contacto'&&await page.locator('.contact-form').isVisible());
 }
 check('Seven distinct service photographs',visuals.size===7);
 await tabs.first().focus();await page.keyboard.press('ArrowRight');check('Tab arrow navigation',await tabs.nth(1).getAttribute('aria-selected')==='true');
 await page.keyboard.press('End');check('Tab End navigation',await tabs.last().getAttribute('aria-selected')==='true');
 await page.keyboard.press('Home');check('Tab Home navigation',await tabs.first().getAttribute('aria-selected')==='true');
 await page.getByRole('button',{name:'Siguiente solución',exact:true}).click();check('Next solution button',await page.locator('.service-content h3').textContent()===titles[1]);
 await tabs.last().click();await page.getByRole('button',{name:'Siguiente solución',exact:true}).click();check('Next solution cycles',await page.locator('.service-content h3').textContent()===titles[0]);
 const summaries=page.locator('.process-accordion summary');
 for(let i=0;i<5;i++){const step=page.locator('.process-accordion details').nth(i);if(!await step.evaluate(e=>e.open))await summaries.nth(i).click();check(`Process ${i+1}: selected step is open`,await step.evaluate(e=>e.open));check(`Process ${i+1}: only one open`,await page.locator('.process-accordion details[open]').count()===1);}
 await summaries.nth(1).focus();await page.keyboard.press('Enter');check('Process responds to keyboard',await page.locator('.process-accordion details').nth(1).evaluate(e=>e.open));
 await page.getByRole('link',{name:'Contacto',exact:true}).click();check('Header contact reaches form',new URL(page.url()).hash==='#contacto');
 const emailLink=page.locator('.contact-channels a[href^="mailto:"]');
 const instagramLink=page.locator('.contact-channels a[href^="https://www.instagram.com/"]');
 check('Official email is visible and linked',await emailLink.isVisible()&&await emailLink.getAttribute('href')==='mailto:escalabusinessco@gmail.com'&&(await emailLink.textContent()).includes('escalabusinessco@gmail.com'));
 check('Official Instagram is visible and linked',await instagramLink.isVisible()&&await instagramLink.getAttribute('href')==='https://www.instagram.com/_escalabusiness/'&&(await instagramLink.textContent()).includes('@_escalabusiness'));
 check('Instagram opens safely in new tab',await instagramLink.getAttribute('target')==='_blank'&&(await instagramLink.getAttribute('rel')).includes('noopener'));
 const form=page.locator('.contact-form');
 check('Contact form has four required fields',await form.locator('input[required]').count()===4);
 check('Native form fallback targets ESCALA email',await form.getAttribute('method')==='POST'&&await form.getAttribute('action')==='https://formsubmit.co/escalabusinessco@gmail.com');
 check('Contact form explains delivery service',await form.getByText(/tus datos se envían a ESCALA mediante FormSubmit/i).isVisible());
 await form.getByRole('button',{name:'Enviar solicitud'}).click();
 check('Empty form blocked by native validation',await form.locator('input[name="name"]').evaluate(e=>!e.validity.valid)&&await form.getByRole('status').count()===0);
 await form.locator('input[name="name"]').fill('Ana Pérez');
 await form.locator('input[name="whatsapp"]').fill('no es teléfono');
 await form.locator('input[name="email"]').fill('ana@example.com');
 await form.locator('input[name="country"]').fill('Colombia');
 await form.getByRole('button',{name:'Enviar solicitud'}).click();
 check('Invalid WhatsApp blocked by native validation',await form.locator('input[name="whatsapp"]').evaluate(e=>!e.validity.valid)&&await form.getByRole('status').count()===0);
 await form.locator('input[name="whatsapp"]').fill('+57 300 123 4567');
 await form.locator('input[name="email"]').fill('correo-invalido');
 await form.getByRole('button',{name:'Enviar solicitud'}).click();
 check('Invalid email blocked by native validation',await form.locator('input[name="email"]').evaluate(e=>!e.validity.valid)&&await form.getByRole('status').count()===0);
 await form.locator('input[name="email"]').fill('ana@example.com');
 let deliveredPayload;
 const deliveryUrl='https://formsubmit.co/ajax/escalabusinessco@gmail.com';
 const cors={'access-control-allow-origin':'*','access-control-allow-methods':'POST, OPTIONS','access-control-allow-headers':'content-type, accept'};
 await page.route(deliveryUrl,route=>{if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers:cors});deliveredPayload=route.request().postDataJSON();return route.fulfill({status:200,contentType:'application/json',headers:cors,body:'{"success":"true"}'});});
 await form.getByRole('button',{name:'Enviar solicitud'}).click();
 await form.getByRole('status').getByText(/solicitud fue recibida/i).waitFor({state:'visible'});
 check('Accepted request shows confirmation',await form.getByRole('status').getByText(/solicitud fue recibida/i).isVisible());
 check('Valid form sends all four fields to delivery service',deliveredPayload?.name==='Ana Pérez'&&deliveredPayload.whatsapp==='+57 300 123 4567'&&deliveredPayload.email==='ana@example.com'&&deliveredPayload.country==='Colombia'&&deliveredPayload._replyto==='ana@example.com');
 check('Accepted request clears fields',await form.locator('input[name="name"]').inputValue()==='');
 await form.screenshot({path:path.join(output,'desktop-contact.png'),animations:'disabled'});
 await page.locator('.contact-section').screenshot({path:path.join(output,'desktop-contact-section.png'),animations:'disabled'});
 await page.unroute(deliveryUrl);
 await page.route(deliveryUrl,route=>{if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers:cors});return route.fulfill({status:200,contentType:'application/json',headers:cors,body:'{"success":"false","message":"This form needs Activation."}'});});
 await form.locator('input[name="name"]').fill('Ana Pérez');
 await form.locator('input[name="whatsapp"]').fill('+57 300 123 4567');
 await form.locator('input[name="email"]').fill('ana@example.com');
 await form.locator('input[name="country"]').fill('Colombia');
 await form.getByRole('button',{name:'Enviar solicitud'}).click();
 await form.getByRole('status').getByText(/pendiente de activación/i).waitFor({state:'visible'});
 check('Activation response does not claim delivery',await form.getByRole('status').getByText(/pendiente de activación/i).isVisible());
 check('Activation response preserves entered data',await form.locator('input[name="name"]').inputValue()==='Ana Pérez');
 await page.unroute(deliveryUrl);
 await page.route(deliveryUrl,route=>{if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers:cors});return route.fulfill({status:502,contentType:'application/json',headers:cors,body:'{"success":"false"}'});});
 expectingContactFailure=true;
 await form.getByRole('button',{name:'Enviar solicitud'}).click();
 await form.getByRole('alert').getByText(/No pudimos enviar/i).waitFor({state:'visible'});
 check('Delivery failure is shown without false success',await form.getByRole('alert').getByText(/No pudimos enviar/i).isVisible());
 check('Delivery failure preserves entered data',await form.locator('input[name="name"]').inputValue()==='Ana Pérez');
 expectingContactFailure=false;
 await page.unroute(deliveryUrl);
 await page.getByRole('button',{name:'Sobre ESCALA',exact:true}).click();check('About dialog opens',await page.locator('dialog[open]').isVisible());await page.getByRole('button',{name:'Cerrar ventana'}).click();
 await page.setViewportSize({width:390,height:844});await page.goto(baseURL,{waitUntil:'networkidle'});
 check('Mobile service tabs visible',await page.getByRole('tablist').isVisible());
 check('Mobile tabs horizontally scroll',await page.locator('.service-tabs').evaluate(e=>e.scrollWidth>e.clientWidth));
 for(let i=0;i<7;i++){await page.getByRole('tab').nth(i).click();check(`Mobile service ${i+1}: selection changes panel`,await page.locator('.service-content h3').textContent()===titles[i]);}
 await page.getByRole('tab').nth(4).click();await page.locator('.service-photo').scrollIntoViewIfNeeded();await page.locator('.service-photo').evaluate(i=>i.decode());await page.locator('.service-explorer').screenshot({path:path.join(output,'mobile-automation.png'),animations:'disabled'});
 const menu=page.getByRole('button',{name:'Abrir menú'});await menu.click();check('Mobile menu opens',await page.getByRole('navigation').isVisible());await page.screenshot({path:path.join(output,'mobile-menu.png')});await page.keyboard.press('Escape');check('Mobile menu Escape restores focus',await menu.evaluate(e=>e===document.activeElement));
 await menu.click();await page.getByRole('navigation').getByRole('link',{name:'Soluciones',exact:true}).click();check('Mobile navigation closes menu',await menu.getAttribute('aria-expanded')==='false');
 await menu.click();await page.getByRole('navigation').getByRole('link',{name:'Contacto',exact:true}).click();check('Mobile contact navigation closes menu and reaches form',await menu.getAttribute('aria-expanded')==='false'&&new URL(page.url()).hash==='#contacto');
 await page.evaluate(()=>{if(document.activeElement instanceof HTMLElement)document.activeElement.blur();});
 await page.locator('.contact-form').screenshot({path:path.join(output,'mobile-contact.png'),animations:'disabled'});
 await page.locator('.contact-section').screenshot({path:path.join(output,'mobile-contact-section.png'),animations:'disabled'});
 check('Body scroll restored',await page.evaluate(()=>document.body.style.overflow!=='hidden'));
 check('Reduced motion respected',await page.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior==='auto'&&getComputedStyle(document.querySelector('.service-art')).animationName==='none'));
 const anchors=await page.locator('a[href^="#"]').evaluateAll(es=>es.every(e=>document.querySelector(e.getAttribute('href'))));check('All anchors exist',anchors);
 check('No browser or HTTP errors',results.errors.length===0);
 results.status='passed';
 }catch(error){results.status='failed';results.failure=error.message;process.exitCode=1;}
 finally{await context.close();fs.writeFileSync(path.join(output,'results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify({status:results.status,checks:results.checks.length,viewports:results.viewports,errors:results.errors,failure:results.failure},null,2));}
})();
